version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_spotify
      - POSTGRES_USER=santi
      - POSTGRES_PASSWORD=buenosaires2024
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgressql/data"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=buenosaires2024
    ports:
      - "5050:80"